### PR TITLE
Fixes #53

### LINKED ISSUE #53: Unexpected exit code when validation fails
When a validation fails, the expected exit code would be different than zero but at the moment it is exiting with zero code.

### PR DESCRIPTION
**Pull request by santiagoaldanondo**

### CODE REVIEW

File: cmd/enval.go [hunk 1]
```diff
@@ -96,12 +96,24 @@ func executeCmd(_ *cobra.Command, _ []string) error {
...
 		os.Exit(1)
 	}
-
+	ok := true
+	for _, result := range results {
+		errs := result.CheckErrors()
+		for _, err := range errs {
+			{
+				ok = false
+				prettyPrintError(err)
```
Comment (hrodes) [inline cmd/enval.go]: the info was already printed. This must just exit 1 without printing as soon as one is not valid

File: pkg/manifestchecker/types.go [hunk 2]
```diff
@@ -175,6 +175,20 @@ func (result *ToolValidationResult) NotParseableVersionOutputCommand(msg string)
 	return result
 }
 
+func (result *ToolValidationResult) CheckErrors() []error {
```
Comment (hrodes) [inline pkg/manifestchecker/types.go]: this function should be just IsValid returning result.IsToolAvailable && result.IsVersionValid && result.IsCommandVersionOutputParseable

File: pkg/exerrors/extended_error.go [hunk 3]
```diff
@@ -40,6 +40,8 @@ const (
 	UnsupportedInputRawVersionEnvalErrorKind
 	FieldVersionKeyNotFoundEnvalErrorKind
 	InvalidCustomSpecsDirEnvalErrorKind
+	InvalidVersionErrorKind
```
Comment (hrodes) [inline pkg/exerrors/extended_error.go]: not needed

File: pkg/exerrors/extended_error.go [hunk 4]
```diff
@@ -40,6 +40,8 @@ const (
...
+	CommandVersionOutputNonParseableErrorKind
```
Comment (hrodes) [inline pkg/exerrors/extended_error.go]: not needed

**Review by hrodes — CHANGES_REQUESTED** [review]

**Review by hrodes — APPROVED** [review]
